[workspace]
members = [
    "packages/rust-dynamodb",
    "packages/rust-cobalt-ssg-site",
    "packages/rust-api-call",
    "packages/rust-server-port",
    "packages/rust-test-lib",
    "packages/rust-test-app"
]
