[package]
name = "rust_dynamodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.12.0"
aws-sdk-dynamodb = "0.12.0"
tokio = { version = "1.19.2", features = ["full"] }
